### ISSUE TITLE
Chiral Center Tokenization 

### ISSUE THREAD

**Issue by rozariwang** [snu-lcbc/atom-in-SMILES#1]
Hi Authors, 

Thanks for the great work! 

I am planning to adopt AIS tokenization in my study, and I found that regarding chiral centers, AIS seems to swap "@" and "@@" (both counterclockwise to clockwise and the other way round) sometimes when it's mapping SMILES to AIS tokens. 

```
test_smiles = "CCC(CC)C(=O)NC[C@@H]1O[C@@H](CC(=O)N2CCN(c3ccccc3OC)CC2)[C@H](O)[C@@H]1O"
encoded_tokens = atomInSmiles.encode(test_smiles)
decoded_smiles = atomInSmiles.decode(encoded_tokens)  
print(f"Original SMILES: {test_smiles}")
print(f"Tokens: {encoded_tokens}")
print(f"Decoded SMILES: {decoded_smiles}")
```

Output: 
```
Original SMILES: CCC(CC)C(=O)NC[C@@H]1O[C@@H](CC(=O)N2CCN(c3ccccc3OC)CC2)[C@H](O)[C@@H]1O
Tokens: [CH3;!R;C] [CH2;!R;CC] [CH;!R;CCC] ( [CH2;!R;CC] [CH3;!R;C] ) [C;!R;CNO] ( = [O;!R;C] ) [NH;!R;CC] [CH2;!R;CN] [[C@H];R;CCO] 1 [O;R;CC] [[C@@H];R;CCO] ( [CH2;!R;CC] [C;!R;CNO] ( = [O;!R;C] ) [N;R;CCC] 2 [CH2;R;CN] [CH2;R;CN] [N;R;CCC] ( [c;R;CCN] 3 [cH;R;CC] [cH;R;CC] [cH;R;CC] [cH;R;CC] [c;R;CCO] 3 [O;!R;CC] [CH3;!R;O] ) [CH2;R;CN] [CH2;R;CN] 2 ) [[C@H];R;CCO] ( [OH;!R;C] ) [[C@H];R;CCO] 1 [OH;!R;C]
Decoded SMILES: CCC(CC)C(=O)NC[C@H]1O[C@@H](CC(=O)N2CCN(c3ccccc3OC)CC2)[C@H](O)[C@H]1O
```

As I am not a chemist, I am unsure whether it is a mistake or just another possible/correct way of rendering the same SMILES strings (btw, all my smiles are canonicalized).

Could you please explain how this happens or if I am implementing it wrong? 

Thanks a lot! 

Best, 
Rosalie

**Comment by ashyrmamatov01** [comment]
Hi Rosalie,

Thank you for your interest in our work!

This discrepancy arises from how RDKit internally handles chiral centers. RDKit assigns counterclockwise ("@") and clockwise ("@@") symbols based on atom's local environment. For instance:

```python
test_smiles = "CCC(CC)C(=O)NC[C@@H]1O[C@@H](CC(=O)N2CCN(c3ccccc3OC)CC2)[C@H](O)[C@@H]1O"

test_mol = Chem.MolFromSmiles(test_smiles)
for atom in test_mol.GetAtoms():
    print(atom.GetIdx(), atom.GetSymbol(), atom.GetChiralTag().name)
```
Output:
```
...
29 C CHI_TETRAHEDRAL_CCW
...
31 C CHI_TETRAHEDRAL_CCW
...
```
In the SMILES, there are two different chiral type symbols for these atoms (e.g., `…[C@H](O)[C@@H]1O`), even though RDKit assigns the same chiral type to both. However, this discrepancy doesn’t always occur. 

Best regards,
Islambek

**Comment by rozariwang** [comment]
Hi @ashyrmamatov01, 

Thank you so much for your reply!  
It's a great tokenizer that we'll incorporate into our study regardless.  

Best, 
Rosalie
